#!/usr/bin/env Rscript
# ===========================================================================
# Figure 2: CCA integration with scRNA-seq
#
# Produces panels B-F. Run from repo root:
#   Rscript fig2/fig2.R                  # run all panels
#   Rscript fig2/fig2.R --only=B,C       # run specific panels
#   Rscript fig2/fig2.R --skip=F         # skip specific panels
#
# Requires:
#   - results/Seurat/GFP_sorted_mousebrain/res0.8/integration/outputs/
#       G4_scRNA_integration.Rds
#       scRNA_Seq_Seurat_object.Rds    (generated by seurat_integration.R)
#       g4_cell_label_preds.Rds
#       scRNA-Seq-FindAllMarkers_output.tsv
# ===========================================================================

# --- Parse CLI flags ---
args <- commandArgs(trailingOnly = TRUE)
panels_all <- c("S1", "B", "C", "D", "E", "F")
run_panels <- panels_all

if (any(grepl("^--only=", args))) {
  run_panels <- unlist(strsplit(sub("^--only=", "", args[grep("^--only=", args)]), ","))
  run_panels <- toupper(trimws(run_panels))
}
if (any(grepl("^--skip=", args))) {
  skip_panels <- unlist(strsplit(sub("^--skip=", "", args[grep("^--skip=", args)]), ","))
  skip_panels <- toupper(trimws(skip_panels))
  run_panels <- setdiff(run_panels, skip_panels)
}
run_panels <- intersect(run_panels, panels_all)
cat("Running panels:", paste(run_panels, collapse = ", "), "\n")

# --- Packages ---
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(ggplot2)
  library(patchwork)
  library(cowplot)
  library(ComplexHeatmap)
  library(dplyr)
  library(viridis)
})

# --- Paths ---
ROOT    <- normalizePath(getwd())
RESULTS <- file.path(ROOT, "results")
DATA    <- file.path(ROOT, "github/data")
OUT     <- file.path(ROOT, "github/fig2", "outputs")
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)

INT_DIR <- file.path(RESULTS, "integration/outputs")

G4_RDS      <- file.path(INT_DIR, "G4_scRNA_integration.Rds")
RNA_RDS     <- file.path(INT_DIR, "scRNA_Seq_Seurat_object.Rds")
PRED_RDS    <- file.path(INT_DIR, "g4_cell_label_preds.Rds")
MARKERS_TSV <- file.path(INT_DIR, "scRNA-Seq-FindAllMarkers_output.tsv")

# --- Load data (lazily) ---
rna <- NULL
g4  <- NULL
pred <- NULL
markers <- NULL

# The manuscript panels use the saved scBridge co-embedding. Recomputing a
# separate UMAP for each Seurat object changes the coordinates and makes the
# modality, prediction, and expression panels impossible to compare directly.
SC_DIR <- file.path(RESULTS, "scBridge/output/GFPsorted_Bartosovic")
COEMBED_FILE <- file.path(SC_DIR, "umap_coembedded.csv")
joint <- NULL

load_rna <- function() {
  if (is.null(rna)) {
    cat("Loading scRNA-seq object...\n")
    rna <<- readRDS(RNA_RDS)
  }
}
load_g4 <- function() {
  if (is.null(g4)) {
    cat("Loading G4 integration object...\n")
    g4 <<- readRDS(G4_RDS)
  }
}
load_pred <- function() {
  if (is.null(pred)) {
    pred <<- readRDS(PRED_RDS)
  }
}
load_markers <- function() {
  if (is.null(markers)) {
    markers <<- read.delim(MARKERS_TSV, check.names = FALSE)
  }
}

load_joint <- function() {
  if (is.null(joint)) {
    load_rna(); load_g4()
    genes_use <- VariableFeatures(rna)
    rna$fig2_modality <- "scRNA-seq"
    g4$fig2_modality <- "G4 scCUT&Tag"
    joint <<- merge(x = rna, y = g4)
    DefaultAssay(joint) <- "RNA"
    joint <- ScaleData(joint, features = genes_use, do.scale = FALSE, verbose = FALSE)
    joint <- RunPCA(joint, features = genes_use, verbose = FALSE)
    joint <- RunUMAP(joint, dims = 1:15, reduction.name = "fig2_umap", verbose = FALSE)
  }
  joint
}

save_fig <- function(plot, name, width = 10, height = 8) {
  ggsave(file.path(OUT, paste0(name, ".pdf")), plot, width = width, height = height)
}

# ===========================================================================
# Panel B: UMAP with cell-type labels (scRNA-seq UMAP)
# ===========================================================================
if ("B" %in% run_panels) {
  cat("== Panel B: co-embedded UMAPs ==\n")
  load_rna(); load_g4()
  joint <- load_joint()
  emb <- as.data.frame(Embeddings(joint, "fig2_umap"))
  names(emb)[1:2] <- c("UMAP1", "UMAP2")
  emb$barcode <- rownames(emb)
  emb$modality <- joint$fig2_modality
  emb$cell_type <- as.character(joint$cell_type)
  emb$prediction <- as.character(joint$pred_cell_type)
  emb$reliability <- NA_real_
  rel <- read.delim(file.path(SC_DIR, "scbridge_reliability.csv"), sep = ",", check.names = FALSE)
  rel <- rel[rel[[1]] != "", ]
  g4_i <- match(emb$barcode, rel[[1]])
  is_g4 <- emb$modality == "G4 scCUT&Tag"
  emb$reliability[is_g4] <- rel$Reliability[g4_i[is_g4]]
  emb$cell_type[is.na(emb$cell_type)] <- "G4 cells"
  emb$prediction <- gsub("Astrocytes", "AST", emb$prediction)
  emb$prediction <- gsub("Oligodendrocytes", "MOL", emb$prediction)
  emb$prediction[is.na(emb$prediction)] <- "unreliable"

  p_mod <- ggplot(emb, aes(UMAP1, UMAP2, color = modality)) +
    geom_point(size = 0.35) +
    scale_color_manual(values = c("scRNA-seq" = "#9ecae1", "G4 scCUT&Tag" = "#fc9272")) +
    labs(title = "Modality", color = NULL) + theme_classic()
  p_type <- ggplot(emb[emb$modality == "scRNA-seq", ], aes(UMAP1, UMAP2, color = cell_type)) +
    geom_point(size = 0.35) + labs(title = "Reference cell type", color = NULL) + theme_classic()
  p_pred <- ggplot(emb[emb$modality == "G4 scCUT&Tag", ], aes(UMAP1, UMAP2, color = prediction)) +
    geom_point(size = 0.45) + labs(title = "Transferred labels", color = NULL) + theme_classic()
  p_rel <- ggplot(emb[emb$modality == "G4 scCUT&Tag", ], aes(UMAP1, UMAP2, color = reliability)) +
    geom_point(size = 0.45) + scale_color_viridis_c(limits = c(0, 1), na.value = "grey80") +
    labs(title = "Integration reliability", color = NULL) + theme_classic()
  save_fig((p_type | p_mod) / (p_pred | p_rel), "panel_B_umap", 14, 12)
}

# ===========================================================================
# Panel C: Prediction score heatmap (viridis)
# ===========================================================================
if ("C" %in% run_panels) {
  cat("== Panel C: Prediction scores ==\n")
  load_pred()
  m <- as.matrix(pred@data)
  m <- m[setdiff(rownames(m), "max"), , drop = FALSE]
  pdf(file.path(OUT, "panel_C_prediction_scores.pdf"), width = 8, height = 6)
   draw(Heatmap(m, name = "prediction score", show_column_names = FALSE,
           col = viridis(100)))
  dev.off()
}

# ===========================================================================
# Panel D1: UMAP of GFP+ cells colored by Seurat cluster
# Panel D2: Cluster vs cell-type overlap heatmap (fraction, viridis)
# ===========================================================================
if ("D" %in% run_panels) {
  cat("== Panel D: Overlap ==\n")
  load_g4()

  # D1: UMAP with Seurat clusters
  p_D1 <- DimPlot(g4, group.by = "seurat_clusters", label = TRUE, repel = TRUE,
                  pt.size = 1.2) +
    ggtitle("GFP+ cells — Seurat clusters") +
    theme_classic() +
    theme(text = element_text(size = 16), axis.text = element_text(size = 14))
  save_fig(p_D1, "panel_D1_umap_clusters", 8, 7)

  # D2: Symmetric overlap score. This is the score used in the older
  # evaluation workflow, rather than a row-normalized composition table.
  pred_labels <- gsub("Astrocytes", "AST", as.character(g4$pred_cell_type))
  pred_labels <- gsub("Oligodendrocytes", "MOL", pred_labels)
  tab <- table(g4$seurat_clusters, pred_labels)
  # Keep only the requested cell types
  target_types <- c("AST", "COP-NFOL", "VLMC", "VEC", "MOL", "OEC", "Pericytes", "OPC")
  tab <- tab[, intersect(target_types, colnames(tab)), drop = FALSE]
  cluster_frac <- prop.table(tab, margin = 1)
  type_frac <- prop.table(tab, margin = 2)
  overlap <- pmin(cluster_frac, type_frac)
  overlap[is.na(overlap)] <- 0
  overlap <- t(overlap)

  pdf(file.path(OUT, "panel_D2_overlap_heatmap.pdf"), width = 8, height = 4)
   draw(Heatmap(overlap, name = "Overlap score", col = viridis(100, option = "D"),
           row_title = "Predicted cell type", column_title = "Seurat cluster",
           cluster_rows = TRUE, cluster_columns = TRUE,
          row_names_gp = gpar(fontsize = 12), column_names_gp = gpar(fontsize = 11),
          column_names_rot = 45,
          cell_fun = function(j, i, x, y, width, height, fill) {
             grid.text(sprintf("%.2f", overlap[i, j]), x, y, gp = gpar(fontsize = 10))
           }))
  dev.off()
}

# ===========================================================================
# Panel E: Reference UMAP plus marker gene violin plots
# ===========================================================================
if ("E" %in% run_panels) {
  cat("== Panel E: Markers ==\n")
  load_rna()
  load_markers()
  top <- markers %>%
    filter(p_val_adj < 0.05, avg_log2FC > 0) %>%
    group_by(cluster) %>%
    slice_max(avg_log2FC, n = 1) %>%
    pull(gene)
  top <- intersect(top, rownames(rna))
   if (length(top) > 0) {
     joint <- load_joint()
     emb <- as.data.frame(Embeddings(joint, "fig2_umap"))
     names(emb)[1:2] <- c("UMAP1", "UMAP2")
     emb$barcode <- rownames(emb)
     rna_umap <- emb[joint$fig2_modality == "scRNA-seq", ]
     rna_umap$cell_type <- as.character(joint$cell_type[joint$fig2_modality == "scRNA-seq"])
     p_umap <- ggplot(rna_umap, aes(UMAP1, UMAP2, color = cell_type)) +
       geom_point(size = 0.35) + labs(title = "scRNA-seq cell types", color = NULL) + theme_classic()
     p_vln <- VlnPlot(rna, features = top, group.by = "cell_type", pt.size = 0, ncol = 3)
     save_fig(p_umap, "panel_E_umap", 8, 7)
     save_fig(p_vln, "panel_E_markers", 14, ceiling(length(top) / 3) * 3)
  } else {
    message("Panel E: no marker genes available")
  }
}

# ===========================================================================
# Panel F: Feature plots per marker gene (scRNA-seq + G4 separately)
# ===========================================================================
if ("F" %in% run_panels) {
  cat("== Panel F: Feature plots ==\n")
  load_rna()
  load_g4()
  load_markers()

  top <- markers %>%
    filter(p_val_adj < 0.05, avg_log2FC > 0) %>%
    group_by(cluster) %>%
    slice_max(avg_log2FC, n = 1) %>%
    pull(gene)
  top <- intersect(top, rownames(rna))

   if (length(top) == 0) {
    message("Panel F: no marker genes available")
  } else {
     joint <- load_joint()
     emb <- as.data.frame(Embeddings(joint, "fig2_umap"))
     names(emb)[1:2] <- c("UMAP1", "UMAP2")
     emb$barcode <- rownames(emb)
     rna_umap <- emb[joint$fig2_modality == "scRNA-seq", ]
     g4_umap <- emb[joint$fig2_modality == "G4 scCUT&Tag", ]
     rna_data <- GetAssayData(rna, assay = "RNA", layer = "data")
     g4_data <- GetAssayData(g4, assay = "GA", layer = "data")
     rna_plots <- list(); g4_plots <- list()
     for (gene in top) {
       if (gene %in% rownames(rna_data)) {
         keep <- match(rna_umap$barcode, colnames(rna))
         keep_ok <- !is.na(keep)
         z <- rna_umap[keep_ok, ]; z$signal <- as.numeric(rna_data[gene, keep[keep_ok]])
         rna_plots[[gene]] <- ggplot(z, aes(UMAP1, UMAP2, color = signal)) + geom_point(size = 0.35) +
           scale_color_viridis(direction = -1) + labs(title = gene, color = "RNA") + theme_classic()
       }
       if (gene %in% rownames(g4_data)) {
         keep <- match(g4_umap$barcode, colnames(g4))
         keep_ok <- !is.na(keep)
         z <- g4_umap[keep_ok, ]; z$signal <- as.numeric(g4_data[gene, keep[keep_ok]])
         g4_plots[[gene]] <- ggplot(z, aes(UMAP1, UMAP2, color = signal)) + geom_point(size = 0.45) +
           scale_color_gradient(low = "white", high = "red") + labs(title = gene, color = "G4") + theme_classic()
       }
     }
     save_fig(wrap_plots(rna_plots, ncol = 3), "panel_F_RNA_featureplots", 14, 10)
     save_fig(wrap_plots(g4_plots, ncol = 3), "panel_F_G4_featureplots", 14, 10)
    message("  Saved ", length(top), " marker gene feature plots (RNA + G4)")
  }
}

# ===========================================================================
# Panel S1: QC violin plots for GFP+ sorted mouse brain
# ===========================================================================
if ("S1" %in% run_panels) {
  cat("== Panel S1: QC violin plots ==\n")
  
  # Load GFP+ data
  SEURAT_GFPPOS <- file.path(DATA, "GSE291468/GSM8836086_GFPpos_Seurat_object.Rds")
  FRAGMENTS_GFPPOS <- file.path(DATA, "GSE291468/GSM8836086_GFP_sorted_mouse_brain/CellRanger/fragments.tsv.gz")
  
  if (!file.exists(SEURAT_GFPPOS) || !file.exists(FRAGMENTS_GFPPOS)) {
    stop("Required files not found:\n  ", SEURAT_GFPPOS, "\n  ", FRAGMENTS_GFPPOS)
  }
  
  seurat <- readRDS(SEURAT_GFPPOS)
  cat(sprintf("  Loaded Seurat object: %s cells, %s features\n", ncol(seurat), nrow(seurat)))
  
  # Compute QC metrics
  cat("  Computing QC metrics...\n")
  fragments <- Signac::CreateFragmentObject(FRAGMENTS_GFPPOS, cells = colnames(seurat))
  seurat[["peaks"]]@fragments <- list(fragments)
  
  if (!"TSS_enrichment" %in% colnames(seurat@meta.data)) {
    seurat <- TSSEnrichment(seurat, fast = TRUE)
    if ("TSS.enrichment" %in% colnames(seurat@meta.data)) {
      seurat$TSS_enrichment <- seurat$TSS.enrichment
    }
  }
  if (!"nucleosome_signal" %in% colnames(seurat@meta.data)) {
    seurat <- NucleosomeSignal(seurat)
  }
  if (!"FRiP" %in% colnames(seurat@meta.data)) {
    total_frags <- CountFragments(FRAGMENTS_GFPPOS, cells = colnames(seurat), verbose = FALSE)
    seurat <- AddMetaData(seurat, metadata = total_frags$reads_count, col.name = "total_fragments")
    seurat <- FRiP(seurat, assay = "peaks", total.fragments = "total_fragments", col.name = "FRiP", verbose = FALSE)
  }
  
  # Generate cluster colors
  n_clusters <- length(levels(seurat$seurat_clusters))
  colors <- c("#9ecae1", "#fc9272", "#a1d99b", "#fdb462", "#b3de69")[1:n_clusters]
  
  # Create QC plots
  make_vln_s1 <- function(feature, ylab_text, log10 = FALSE, ylim = NULL) {
    p <- VlnPlot(seurat, group.by = "seurat_clusters", features = feature, pt.size = 0.1) +
      scale_fill_manual(values = colors) +
      ggtitle("") + xlab("cluster") + ylab(ylab_text) +
      stat_summary(fun = median, geom = "crossbar", width = 0.4, linewidth = 0.4, color = "black") +
      stat_summary(fun = mean, geom = "point", size = 3, color = "black") +
      theme_classic() +
      theme(axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
            axis.text.y = element_text(size = 12)) +
      NoLegend()
    if (log10) {
      p <- p + scale_y_log10()
    } else if (!is.null(ylim)) {
      p <- p + coord_cartesian(ylim = ylim)
    }
    p
  }
  
  plots <- list(
    make_vln_s1("nFeature_peaks", "nFeature (peaks)", log10 = TRUE),
    make_vln_s1("nCount_peaks", "nCount (peaks)", log10 = TRUE),
    make_vln_s1("TSS_fragments", "TSS fragments", log10 = TRUE),
    make_vln_s1("mitochondrial", "mitochondrial fragments", log10 = TRUE),
    make_vln_s1("FRiP", "Fraction of reads in peaks", ylim = c(0, 0.15)),
    make_vln_s1("TSS_enrichment", "TSS enrichment", ylim = c(0, 10)),
    make_vln_s1("nucleosome_signal", "Nucleosome signal", ylim = c(0, 3))
  )
  
  p_combined <- cowplot::plot_grid(plotlist = plots, ncol = 2, nrow = 4)
  ggsave(file.path(OUT, "panel_S1_qc_GFPpos.pdf"), p_combined, width = 12, height = 16, dpi = 300)
  cat("  Saved panel_S1_qc_GFPpos.pdf\n")
}

cat("\nAll Figure 2 outputs written to ", OUT, "/\n")
